CREATE DATABASE IF NOT EXISTS hello DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE hello;
--  TODO: just sample
CREATE TABLE IF NOT EXISTS hello_sample (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)